# Generated by Django 4.2.30 on 2026-09-01 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_company_id", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("activa", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semana",
                    models.DateField(
                        help_text="Monday of the ISO week this budget applies to."
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="presupuestos.sucursal",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="presupuestos.tipogasto",
                    ),
                ),
            ],
            options={
                "ordering": ["-semana", "sucursal", "tipo_gasto"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="presupuestos.sucursal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GastoReal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_move_id", models.IntegerField()),
                ("odoo_move_line_id", models.IntegerField(unique=True)),
                ("factura_numero", models.CharField(max_length=100)),
                ("proveedor_odoo_id", models.IntegerField(blank=True, null=True)),
                ("proveedor_nombre", models.CharField(max_length=255)),
                ("fecha_factura", models.DateField()),
                (
                    "semana",
                    models.DateField(
                        help_text="Monday of the ISO week fecha_factura falls in."
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            ("not_paid", "Not paid"),
                            ("in_payment", "In payment"),
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                            ("reversed", "Reversed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos",
                        to="presupuestos.sucursal",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to="presupuestos.tipogasto",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_factura"],
            },
        ),
        migrations.CreateModel(
            name="CuentaContableTipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_account_id", models.IntegerField(unique=True)),
                ("odoo_account_name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="presupuestos.tipogasto",
                    ),
                ),
            ],
            options={
                "ordering": ["odoo_account_name"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaProductoTipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_category_id", models.IntegerField(unique=True)),
                ("odoo_category_name", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="presupuestos.tipogasto",
                    ),
                ),
            ],
            options={
                "ordering": ["odoo_category_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="presupuesto",
            constraint=models.UniqueConstraint(
                fields=("sucursal", "tipo_gasto", "semana"),
                name="unique_presupuesto_sucursal_tipo_semana",
            ),
        ),
        migrations.AddIndex(
            model_name="gastoreal",
            index=models.Index(
                fields=["sucursal", "semana"], name="presupuesto_sucursa_90e4b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gastoreal",
            index=models.Index(
                fields=["sucursal", "tipo_gasto", "semana"],
                name="presupuesto_sucursa_d90f5d_idx",
            ),
        ),
    ]
