# Generated by Django 4.2.30 on 2026-09-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0002_seed_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproductotipogasto",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="presupuestos.tipogasto",
            ),
        ),
        migrations.AlterField(
            model_name="cuentacontabletipogasto",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="presupuestos.tipogasto",
            ),
        ),
    ]
