# Generated by Django 4.2.30 on 2026-09-01 20:56

from django.db import migrations

CATEGORIAS = ["Costo de Ventas", "Gasto Operativo"]

# (nombre, categoria) - starting point proposed from real Odoo purchase data,
# fully editable (rename, recategorize, add more) from the app afterward.
TIPOS_GASTO = [
    ("Alimentos", "Costo de Ventas"),
    ("Bebidas", "Costo de Ventas"),
    ("Empaque y Limpieza", "Gasto Operativo"),
    ("Mantenimiento", "Gasto Operativo"),
    ("Renta y Arrendamiento", "Gasto Operativo"),
    ("Nomina y Personal", "Gasto Operativo"),
    ("Combustibles y Transporte", "Gasto Operativo"),
    ("Servicios Publicos", "Gasto Operativo"),
    ("Servicios Profesionales", "Gasto Operativo"),
    ("Administrativo y Oficina", "Gasto Operativo"),
    ("Publicidad y Marketing", "Gasto Operativo"),
    ("Otros / Sin Clasificar", "Gasto Operativo"),
]


def seed(apps, schema_editor):
    Categoria = apps.get_model("presupuestos", "Categoria")
    TipoGasto = apps.get_model("presupuestos", "TipoGasto")

    categorias = {}
    for nombre in CATEGORIAS:
        obj, _ = Categoria.objects.get_or_create(nombre=nombre)
        categorias[nombre] = obj

    for nombre, categoria_nombre in TIPOS_GASTO:
        TipoGasto.objects.get_or_create(nombre=nombre, defaults={"categoria": categorias[categoria_nombre]})


def unseed(apps, schema_editor):
    TipoGasto = apps.get_model("presupuestos", "TipoGasto")
    Categoria = apps.get_model("presupuestos", "Categoria")
    TipoGasto.objects.filter(nombre__in=[n for n, _ in TIPOS_GASTO]).delete()
    Categoria.objects.filter(nombre__in=CATEGORIAS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0004_categoria_tipogasto_categoria"),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
