# Generated by Django 4.2.30 on 2026-09-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0005_seed_categorias_y_tipos_gasto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nombre"],
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="categoriaproductotipogasto",
            options={
                "ordering": ["odoo_category_name"],
                "verbose_name": "categoria de producto -> tipo de gasto",
                "verbose_name_plural": "categorias de producto -> tipo de gasto",
            },
        ),
        migrations.AlterModelOptions(
            name="cuentacontabletipogasto",
            options={
                "ordering": ["odoo_account_name"],
                "verbose_name": "cuenta contable -> tipo de gasto",
                "verbose_name_plural": "cuentas contables -> tipo de gasto",
            },
        ),
        migrations.AlterModelOptions(
            name="gastoreal",
            options={
                "ordering": ["-fecha_factura"],
                "verbose_name": "gasto real",
                "verbose_name_plural": "gastos reales",
            },
        ),
        migrations.AlterModelOptions(
            name="perfilusuario",
            options={
                "verbose_name": "perfil de usuario",
                "verbose_name_plural": "perfiles de usuario",
            },
        ),
        migrations.AlterModelOptions(
            name="presupuesto",
            options={
                "ordering": ["-semana", "sucursal", "tipo_gasto"],
                "verbose_name": "presupuesto",
                "verbose_name_plural": "presupuestos",
            },
        ),
        migrations.AlterModelOptions(
            name="sucursal",
            options={
                "ordering": ["nombre"],
                "verbose_name": "sucursal",
                "verbose_name_plural": "sucursales",
            },
        ),
        migrations.AlterModelOptions(
            name="tipogasto",
            options={
                "ordering": ["categoria__nombre", "nombre"],
                "verbose_name": "tipo de gasto",
                "verbose_name_plural": "tipos de gasto",
            },
        ),
    ]
