# Generated by Django 4.2.30 on 2026-09-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0006_alter_categoria_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuesto",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                help_text="Deja en blanco para capturar el presupuesto total de la semana sin desglosar por tipo de gasto.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presupuestos",
                to="presupuestos.tipogasto",
            ),
        ),
    ]
