# Generated by Django 4.2.30 on 2026-09-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0007_alter_presupuesto_tipo_gasto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presupuesto",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                help_text="Deja en blanco para capturar 'todo lo demas': ese monto se reparte en partes iguales entre los tipos de gasto que NO tengan su propio presupuesto capturado para esta misma sucursal y semana.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presupuestos",
                to="presupuestos.tipogasto",
            ),
        ),
    ]
