# Generated by Django 4.2.30 on 2026-09-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0008_alter_presupuesto_tipo_gasto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gastoreal",
            options={
                "ordering": ["-fecha_pago"],
                "verbose_name": "gasto real",
                "verbose_name_plural": "gastos reales",
            },
        ),
        migrations.AddField(
            model_name="gastoreal",
            name="fecha_pago",
            field=models.DateField(
                blank=True,
                help_text="Fecha real de pago (la mas reciente si hubo varios pagos). Define semana.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastoreal",
            name="monto_factura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total de la factura completa (account.move.amount_total), igual en todas sus lineas.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastoreal",
            name="monto_pagado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Suma de los pagos reconciliados con esta factura. Si no coincide con monto_factura, revisar a mano: puede ser un pago compartido con otras facturas.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gastoreal",
            name="fecha_factura",
            field=models.DateField(
                help_text="Fecha de la factura en Odoo (invoice_date). Solo referencia."
            ),
        ),
        migrations.AlterField(
            model_name="gastoreal",
            name="semana",
            field=models.DateField(
                help_text="Monday of the ISO week fecha_pago falls in."
            ),
        ),
    ]
