# Generated by Django 4.2.30 on 2026-09-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0009_alter_gastoreal_options_gastoreal_fecha_pago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastoreal",
            name="monto",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Linea con IVA incluido (Odoo price_total, no price_subtotal) - es el efectivo real pagado.",
                max_digits=12,
            ),
        ),
    ]
