# Generated by Django 4.2.30 on 2026-09-07

from django.db import migrations, models
import django.db.models.deletion


def borrar_presupuestos_existentes(apps, schema_editor):
    # Switching Presupuesto from weekly to monthly capture - the existing
    # weekly rows aren't meaningful under the new "mes" field (a Monday
    # date isn't a month), and the user confirmed starting fresh rather
    # than trying to backfill/convert them.
    Presupuesto = apps.get_model("presupuestos", "Presupuesto")
    Presupuesto.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0010_alter_gastoreal_monto"),
    ]

    operations = [
        migrations.RunPython(borrar_presupuestos_existentes, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="presupuesto",
            name="unique_presupuesto_sucursal_tipo_semana",
        ),
        migrations.RemoveField(
            model_name="presupuesto",
            name="semana",
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="mes",
            field=models.DateField(
                default="2026-01-01",
                help_text="First day of the calendar month this budget applies to (e.g. 2026-08-01).",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="presupuesto",
            constraint=models.UniqueConstraint(
                fields=("sucursal", "tipo_gasto", "mes"), name="unique_presupuesto_sucursal_tipo_mes"
            ),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                help_text="Deja en blanco para capturar 'todo lo demas': ese monto se reparte en partes iguales entre los tipos de gasto que NO tengan su propio presupuesto capturado para esta misma sucursal y mes.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="presupuestos",
                to="presupuestos.tipogasto",
            ),
        ),
        migrations.AlterModelOptions(
            name="presupuesto",
            options={
                "ordering": ["-mes", "sucursal", "tipo_gasto"],
                "verbose_name": "presupuesto",
                "verbose_name_plural": "presupuestos",
            },
        ),
    ]
