# Generated by Django 4.2.30 on 2026-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0011_presupuesto_captura_mensual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCatalogos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permitir_carga_inicial",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta activo, la proxima importacion de la plantilla de catalogos borra Categorias, Tipos de gasto, Cuentas contables -> tipo de gasto y Categorias de producto -> tipo de gasto, y los reemplaza por completo con el contenido del Excel. Se apaga solo despues de una carga exitosa; solo se reactiva aqui, a mano.",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuracion de catalogos",
                "verbose_name_plural": "configuracion de catalogos",
            },
        ),
    ]
