# Generated by Django 4.2.30 on 2026-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestos", "0012_configuracioncatalogos"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastoreal",
            name="fecha_recepcion",
            field=models.DateField(
                blank=True,
                help_text="Purchase order's effective_date (goods actually received). Only set when orden_compra is set; determines semana for PO-linked lines instead of fecha_pago.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gastoreal",
            name="orden_compra",
            field=models.CharField(
                blank=True,
                help_text="Odoo purchase.order name (invoice_origin). Blank if this line has no linked purchase order (a direct/service expense, e.g. rent, payroll, utilities).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gastoreal",
            name="semana",
            field=models.DateField(
                help_text="Monday of the managing week - fecha_recepcion if orden_compra is set, else fecha_pago."
            ),
        ),
    ]
