# Generated by Django 4.2.30 on 2026-10-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "presupuestos",
            "0013_gastoreal_fecha_recepcion_gastoreal_orden_compra_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaPresupuestoTipoGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_gasto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="presupuestos.tipogasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta de presupuesto -> tipo de gasto",
                "verbose_name_plural": "cuentas de presupuesto -> tipo de gasto",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="PresupuestoCuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.DateField(
                        help_text="First day of the month (Odoo's own budget item date)."
                    ),
                ),
                ("cuenta_codigo", models.CharField(max_length=30)),
                ("cuenta_nombre", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("odoo_budget_id", models.IntegerField()),
                ("sincronizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos_cuenta",
                        to="presupuestos.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "presupuesto por cuenta (Odoo)",
                "verbose_name_plural": "presupuestos por cuenta (Odoo)",
                "ordering": ["sucursal", "-mes", "cuenta_codigo"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "mes"],
                        name="presupuesto_sucursa_90ba6c_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="presupuestocuenta",
            constraint=models.UniqueConstraint(
                fields=("sucursal", "mes", "cuenta_codigo"),
                name="unique_presupuestocuenta_sucursal_mes_cuenta",
            ),
        ),
    ]
